version: '3.3'
services:
  database:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: password
    volumes:
     - ./database/volume:/var/lib/postgresql/data
    ports:
     - '5432:5432'
  redis:
    image: redis:latest
    command:
     - redis-server
     - --requirepass
     - password
    ports:
     - '6379:6379'
  # manager:
  #   image:  musicorum/resource-manager:latest
  #   ports:
  #     - '8080:8080'
  #   environment:
  #     # must load .env in terminal environment before
  #     CORS_ORIGINS: '*'
  #     DATABASE_URL: postgres://postgres:password@database:5432/resources
  #     LASTFM_KEY: '$LASTFM_KEY'
  #     PORT: '8080'
  #     REDIS_HOST: redis
  #     REDIS_PASS: password
  #     REDIS_PORT: '6379'
  #     SPOTIFY_ID: '$SPOTIFY_ID'
  #     SPOTIFY_SECRET: '$SPOTIFY_SECRET'