version: '3.3'
services:
  database:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: password
    ports:
     - '5432:5432'
    volumes:
     - ./database/volume:/var/lib/postgresql/data
  redis:
    image: redis:latest
    command:
     - redis-server
     - --requirepass
     - password
    ports:
     - '6379:6379'
  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    environment:
      -  GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped
    ports:
      - 3000:3000
  prometheus:
    image: prom/prometheus
    user: root
    container_name: prometheus
    hostname: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
    extra_hosts:
      - "host.docker.internal:host-gateway"